title: Arbace
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

Arbace:
  custom_css:
    - "assets/css/_custom.scss"

url: https://arbace.github.io

aux_links:
  Template Repository: https://github.com/lux-e/arbace
